const notificationKeys = {
    COIN_CREATED: 'COIN_CREATED',
    COIN_SENT: 'COIN_SENT',
    COIN_RECEIVED: 'COIN_RECEIVED',
    COIN_MINTED: 'COIN_MINTED',
    DAO_CREATED:'DAO_CREATED',
    DAO_COIN_CREATED: 'DAO_COIN_CREATED',
    DAO_COIN_SENT: 'DAO_COIN_SENT',
    DAO_COIN_RECEIVED: 'DAO_COIN_RECEIVED',
    DAO_COIN_MINTED: 'DAO_COIN_MINTED',
    DAO_ADMIN_ADDED: 'DAO_ADMIN_ADDED',
    DAO_MEMBER_JOINED: 'DAO_MEMBER_JOINED',
    DAO_MEMBER_KICKED: 'DAO_MEMBER_KICKED',
    DAO_MEMBER_DEMOTED: 'DAO_MEMBER_DEMOTED',
    DAO_MEMBER_PROMOTED: 'DAO_MEMBER_PROMOTED',
    DAO_CROWDSALE_CREATED: 'DAO_CROWDSALE_CREATED',
    CROWDSALE_CREATED: 'CROWDSALE_CREATED',
    CROWDSALE_UNLOCKED: 'CROWDSALE_UNLOCKED',
    DAO_CROWDSALE_UNLOCKED: 'DAO_CROWDSALE_UNLOCKED',
    CROWDSALE_JOINED: 'CROWDSALE_JOINED',
    CROWDSALE_REFUNDED: 'CROWDSALE_REFUNDED',
    CROWDSALE_STOPPED: 'CROWDSALE_STOPPED',
    DAO_CROWDSALE_STOPPED: 'DAO_CROWDSALE_STOPPED',
    WALLET_READY: 'WALLET_READY',

};

export default notificationKeys;